# Generated by Django 5.0.8 on 2024-08-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mostruario", "0004_item_category_item_created_at_item_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="description",
        ),
    ]
