# Generated by Django 5.0.8 on 2024-09-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mostruario", "0006_alter_item_category_alter_item_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.CharField(
                choices=[
                    ("Amigurumi", "Amigurumi"),
                    ("Roupas", "Roupas"),
                    ("Bolsas", "Bolsas"),
                ],
                max_length=50,
                verbose_name="Categoria",
            ),
        ),
    ]
