# Generated by Django 5.0.8 on 2024-09-05 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mostruario", "0007_alter_item_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="item",
            name="photo",
        ),
        migrations.CreateModel(
            name="ItemPhoto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.ImageField(upload_to="items/", verbose_name="Foto")),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="photos",
                        to="mostruario.item",
                    ),
                ),
            ],
        ),
    ]
