# Generated by Django 5.0.8 on 2024-09-18 19:42

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mostruario", "0008_remove_item_photo_itemphoto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="itemphoto",
            name="photo",
            field=cloudinary.models.CloudinaryField(
                max_length=255, verbose_name="Foto"
            ),
        ),
    ]
